name: login-client | Build & Deploy to Azure

on:
  push:
    branches: ["main"]
    paths:
      - "login-client/**"
      - ".github/workflows/login-client-cicd.yml"
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-salud-ips
  WEBAPP_NAME: web-login-client-salud-ips
  ACR_NAME: acrsaludipsobri
  IMAGE_NAME: login-client:1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout
        uses: actions/checkout@v4

      - name: üîê Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: üê≥ Build image in ACR (login-client)
        run: |
          az acr build \
            --registry $ACR_NAME \
            --image $IMAGE_NAME \
            --file login-client/Dockerfile \
            login-client

      - name: üîÅ Restart Web App
        run: |
          az webapp restart \
            --resource-group $RESOURCE_GROUP \
            --name $WEBAPP_NAME
